### ISSUE TITLE
Activity is not always being correct

### ISSUE THREAD

**Issue by piggydoughnut** [TokelPlatform/tokel_dapp#156]
## Expected Behavior

Recipients and senders are populated in bitgo from the getTransactionsDecoded

## Current Behavior

```
Error: OP_RETURN c5b982d0bbe52e161fa6f1a6a6a2393afa4ef6ad has no matching Address
    at Object.fromOutputScript (/Users/dariah/Documents/Dev/tokel/test/tokel_app/src/electron/node_modules/@tokel/bitgo-komodo-cc-lib/src/address.js:80:9)
    at /Users/dariah/Documents/Dev/tokel/test/tokel_app/src/electron/node_modules/@tokel/bitgo-komodo-cc-lib/cc/txParser.js:28:30
    at Array.filter (<anonymous>)
    at decodeTransactionData (/Users/dariah/Documents/Dev/tokel/test/tokel_app/src/electron/node_modules/@tokel/bitgo-komodo-cc-lib/cc/txParser.js:25:24)
    at /Users/dariah/Documents/Dev/tokel/test/tokel_app/src/electron/node_modules/@tokel/bitgo-komodo-cc-lib/cc/ccutils.js:513:21
    at Array.forEach (<anonymous>)
    at Object.getTransactionsManyDecoded (/Users/dariah/Documents/Dev/tokel/test/tokel_app/src/electron/node_modules/@tokel/bitgo-komodo-cc-lib/cc/ccutils.js:512:33)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
{
```

## Steps to Reproduce

1. login using WIF `test`. There are two transactions which are received but in fact they are sent.

## Possible Solution (Not obligatory)

Maybe we can pull data from explorer for some of the transactions or figure out how else to identify where they came from, apart from reading form pubscript which throws the above errors.

**Comment by piggydoughnut** [comment]
fixed already previously. OP_RETURN - it is what it is, some txs dont have addresses in them
